<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dynamic_reconfigure</name>
  <version>1.0.0</version>
  <description>dynamic_reconfigure package is a rviz plugin designed to change the parameters on the fly.</description>
  <maintainer email="shahjesal1510@gmail.com">jesxshah</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>rviz_common</depend>
  <depend>qtbase5-dev</depend>
  <depend>pluginlib</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
    <rviz plugin="${prefix}/dynamic_reconfigure.xml"/>  
  </export>
</package>